image: java:8
pipelines:
  default:
    - step:
        script:
        # Download and unzip android sdk
          - wget https://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
          - tar zxvf android-sdk*.tgz
        # Define android Home and add PATHs (After that you can run "android")
          - export ANDROID_HOME="/opt/atlassian/pipelines/agent/build/android-sdk-linux"
          - export PATH="$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$PATH"
        # Accept all licences http://stackoverflow.com/questions/38096225/automatically-accept-all-sdk-licences 
          - mkdir "${ANDROID_HOME}/licenses" || true
          - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "${ANDROID_HOME}/licenses/android-sdk-license"
        # Build apk
          - chmod a+x gradlew
          - ./gradlew assembleDebug